<<<<<<< HEAD
log_file_path:
  local: ./tmp/crawler.log
  test: ./tmp/crawler.log
  development: /home/yukkuri/log/crawler.log
  staging: /home/yukkuri/log/crawler.log
  production: /home/yukkuri/log/crawler.log
=======
default: &default
  part_one_tag: "ゆっくり実況プレイpart1リンク or VOICEROID実況プレイPart1リンク"

local:
  <<: *default
  host: 127.0.0.1
  log_file_path: ./tmp/crawler.log

test:
  <<: *local

development:
  <<: *default
  host: 192.168.33.12
  log_file_path: /home/yukkuri/log/crawler.log

staging:
  host: REPLACEME
  <<: *development

production:
  host: REPLACEME
  <<: *development
>>>>>>> fix
